os:
matrix:
  include:
  - os: linux
    language: java
    jdk: oraclejdk8
  - os: linux
    language: java
    jdk: openjdk11
  - os: osx
    language: java
    jdk: oraclejdk9
  - os: windows
    language: shell
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then choco install jdk8  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin" ; fi
script:
  - if [[ "$TRAVIS_OS_NAME != "windows" ]] ; then ./gradlew test build ; else gradlew.bat ; fi
branches:
  only:
  - master