os:
  - linux
  - osx
  - windows
language: java
jdk:
  - oraclejdk8
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then choco install jdk8  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin" ; fi
script: ./gradlew test build
branches:
  only:
  - master