os:
matrix:
  include:
  - os: linux
    language: java
    jdk: oraclejdk8
  - os: linux
    language: java
    jdk: openjdk11
  - os: osx
    language: java
    jdk: openjdk8
  - os: windows
    jdk: oraclejdk8
    language: sh
before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then ls /c/Program\ Files ; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin" ; fi

after_script:
  - if [[ $gradle_return == "0" ]] ; then travis_terminate 0 ; else travis_terminate 1 ; fi
script:
  - ./gradlew test build ; gradle_return=$?
branches:
  only:
  - master