os:
matrix:
  include:
  - os: linux
    language: java
    jdk: oraclejdk8
  - os: linux
    language: java
    jdk: openjdk11
  - os: osx
    language: java
    jdk: openjdk11
  - os: windows
    language: shell
    jdk: openjdk11
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then choco install jdk8  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin" ; fi
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then taskkill -F -im java.exe  ; fi
  - if [[ $gradle_return == "0" ]] ; then travis_terminate 0 ; else travis_terminate 1 ; fi
script:
  - ./gradlew test build ; gradle_return=$?
branches:
  only:
  - master